#!/bin/sh

set -e

export PATH=/usr/local/bin:$PATH

TMPDIR=".git"
TMPFILE=`mktemp -t tags` || exit 1

trap "rm -f $TMPFILE" EXIT
ctags --tag-relative --recurse -f $TMPFILE --exclude=.git --languages=-javascript,sql
mv $TMPFILE "$TMPDIR/tags"
