#!/bin/bash

# Install all dotfiles into the home directory

set -e
set -o pipefail

DOTFILES_ROOT="$(pwd)"

if [ -z "$1" ]; then
  DEST_ROOT=$HOME
else
  DEST_ROOT="$1"
fi

find "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -print0 | while IFS= read -r -d '' source
do
  dest="${DEST_ROOT}/.$(basename "${source%.*}")"

  if [ -e "$dest" ]; then
    mv -fv "$dest" "${dest}.backup"
  fi

  ln -svf "$source" "$dest"
done
