#!/bin/bash

# applies https://github.com/OfflineIMAP/offlineimap3/pull/139 to offlineimap

set -e
set -o pipefail

OFFLINEIMAP_VERSION=8.0.0_2
PYTHON_VERSION=python3.12

patch /opt/homebrew/Cellar/offlineimap/$OFFLINEIMAP_VERSION/libexec/lib/$PYTHON_VERSION/site-packages/offlineimap/folder/LocalStatusSQLite.py \
  "${ZSH:-$HOME/.dotfiles}/offlineimap/offlineimap-pr139.patch"
